name: Detection stationnement IT

on:
  schedule:
    - cron: "10,25,40,55 * * * *"
  workflow_dispatch:

env:
  API_URL: ${{ secrets.DETECTION_API_URL }}
  API_KEY: ${{ secrets.DETECTION_API_KEY }}
  IN_STATUS_PAGE_ID: ${{ secrets.INSTATUS_PAGE_ID }}
  IN_STATUS_API_KEY: ${{ secrets.INSTATUS_API_KEY }}
  IN_STATUS_500_TMPL_ID: ${{ secrets.INSTATUS_500_TMPL_ID }}
  IN_STATUS_RESOLVE_500_TMPL_ID: ${{ secrets.INSTATUS_RESOLVE_500_TMPL_ID }}
  IN_STATUS_IMAGE_SOURCES_DEGRADED_TMPL_ID: ${{ secrets.IN_STATUS_IMAGE_SOURCES_DEGRADED_TMPL_ID }}
  IN_STATUS_IMAGE_SOURCES_RESTORED_TMPL_ID: ${{ secrets.IN_STATUS_IMAGE_SOURCES_RESTORED_TMPL_ID }}

jobs:
  detection-creation:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          ref: prod

      - name: Generate detection_stationnement_e2_id and store inside file
        run: |
          detection_sync_e2_id=$(uuidgen)
          echo "$detection_sync_e2_id" > detection_stationnement_e2_id.txt
          echo "detection_sync_e2_id=$detection_sync_e2_id" >> $GITHUB_ENV
          echo "Generated detection_sync_e2_id: '$detection_sync_e2_id'"

      - name: Cache detection_stationnement_e2_id for completion run
        uses: actions/cache@v4
        with:
          path: detection_stationnement_e2_id.txt
          key: detection_stationnement_e2_id-cache-${{ runner.os }}-${{ github.sha }}

      - name: Send POST /detections/*/sync request for BP_STATIONNEMENT model only
        run: |
          echo "Reusing detection_sync_e2_id: '$detection_sync_e2_id'"
          response_file="detection-response.json"
          
          http_code=$(curl -s -w "%{http_code}" -X POST "$API_URL/detections/$detection_sync_e2_id/sync" \
          -H "Content-Type: application/json" \
          -H "x-api-key: $API_KEY" \
          -H "x-test-request: true" \
          --data "@.github/workflows/detection-stationnement-request-sync.json" \
          -o "$response_file")
          
          echo "HTTP Response Code: $http_code"
          echo "Response Body:"
              cat $response_file
          
          incident_list=$(curl -s -X GET "https://api.instatus.com/v1/$IN_STATUS_PAGE_ID/incidents" \
          -H "Authorization: Bearer $IN_STATUS_API_KEY")
          
          internal_incident_lines=$(echo "$incident_list" | jq -r '
          .[]
          | select(.status != "RESOLVED" and
          (.name == "Internal server error"))
          | "\(.id)|\(.name)|\(.status)"')
          
          image_performance_incident_lines=$(echo "$incident_list" | jq -r '
          .[]
          | select(.status != "RESOLVED" and
          (.name == "Image sources performance degradation"))
          | "\(.id)|\(.name)|\(.status)"')
          
          if [ "${http_code:-0}" -ne 200 ]; then
            echo "Response Body:"
              cat $response_file
          
            if [ "$http_code" -eq 504 ]; then
              echo "Gateway Timeout detected (504)"
              if grep -q "Image sources" "$response_file"; then
                if [[ -z "$image_performance_incident_lines" ]]; then
                  echo "Creating Instatus incident ..."
                  in_status_response=$(curl -s -o in-status-response.json -w "%{http_code}" \
                  -X POST https://api.instatus.com/v1/$IN_STATUS_PAGE_ID/incidents/$IN_STATUS_IMAGE_SOURCES_DEGRADED_TMPL_ID \
                  -H "Authorization: Bearer $IN_STATUS_API_KEY")
                  incident_id=$(jq -r '.id' in-status-response.json)
                  echo "InStatus incident identifier: '$incident_id'"
                fi
                exit 1
              fi
            fi
          
            if [[ -z "$internal_incident_lines" ]]; then
              echo "No active 'Internal server error' incident. Creating one..."
              in_status_response=$(curl -s -o in-status-response.json -w "%{http_code}" \
              -X POST https://api.instatus.com/v1/$IN_STATUS_PAGE_ID/incidents/$IN_STATUS_500_TMPL_ID \
              -H "Authorization: Bearer $IN_STATUS_API_KEY")
              incident_id=$(jq -r '.id' in-status-response.json)
              echo "InStatus incident identifier: '$incident_id'"
            else
                echo "Incident already exists. Not creating another one."
            fi
            exit 1
          fi
          
          stepName=$(jq -r '.step.name' "$response_file")
          progression=$(jq -r '.step.status.progression' "$response_file")
          health=$(jq -r '.step.status.health' "$response_file")

          errors=""
          
          if [[ "$stepName" != "MACHINE_DETECTION" ]]; then
            errors+=" detection is not in step MACHINE_DETECTION but : $stepName"$'\n'
          fi

          if [[ "$progression" != "FINISHED" ]]; then
            errors+=" detection progression is not FINISHED but : $progression"$'\n'
          fi

          if [[ "$health" != "SUCCEEDED" ]]; then
            errors+=" detection health is not SUCCEEDED but : $health"$'\n'
          fi

          if [[ -n "$errors" ]]; then
            echo "Response contains unexpected values"
            echo "general errors : $errors"
            if [[ -z "$internal_incident_lines" ]]; then
              echo "No active 'Internal server error' incident. Creating one..."
              in_status_response=$(curl -s -o in-status-response.json -w "%{http_code}" \
              -X POST https://api.instatus.com/v1/$IN_STATUS_PAGE_ID/incidents/$IN_STATUS_500_TMPL_ID \
              -H "Authorization: Bearer $IN_STATUS_API_KEY")

              incident_id=$(jq -r '.id' in-status-response.json)
              echo "InStatus incident identifier: '$incident_id'"
            else
                echo "Incident already exists. Not creating another one."
            fi
            exit 1
          else
            if [[ -n "$internal_incident_lines" ]]; then
              while IFS='|' read -r id incident_name incident_status; do
                if [[ "$incident_name" == *"Internal server error"* ]]; then
                  echo "Resolving internal server error incident: $id"
                  curl -s -o /dev/null -X POST \
                  https://api.instatus.com/v2/$IN_STATUS_PAGE_ID/incidents/"$id"/incident-updates/$IN_STATUS_RESOLVE_500_TMPL_ID \
                  -H "Authorization: Bearer $IN_STATUS_API_KEY"
                fi
              done <<< "$internal_incident_lines"
            fi
            if [[ -n "$image_performance_incident_lines" ]]; then
              while IFS='|' read -r id incident_name incident_status; do
                if [[ "$incident_name" == *"Image sources performance degradation"* ]]; then
                  echo "Resolving Image sources performance degradation: $id"
                  curl -s -o /dev/null -X POST \
                  https://api.instatus.com/v2/$IN_STATUS_PAGE_ID/incidents/"$id"/incident-updates/$IN_STATUS_IMAGE_SOURCES_RESTORED_TMPL_ID \
                  -H "Authorization: Bearer $IN_STATUS_API_KEY"
                fi
              done <<< "$image_performance_incident_lines"
            fi
          fi